title = "XR Bitcoin Cash"
description = "XR Bitcoin Cash cryptocurrency metadata for Xamine wallet scraping and integration."
version = "1.0.0"
domain = "xrbitcoincash.com"
source = "https://github.com/XRBitcoinCash/XRBitcoinCash"
maintainer = "XRBitcoinCash"
contact_email = "your@email.com"

[process]
name = "XR Bitcoin Cash Integration"
type = "cryptocurrency"
platform = "github"
repository = "https://github.com/XRBitcoinCash/XRBitcoinCash"
documentation = "https://github.com/XRBitcoinCash/XRBitcoinCash/blob/main/README.md"
status = "active"
last_updated = "2025-08-04"

[metadata]
license = "MIT"
language = ["Python", "JavaScript"]
tags = ["cryptocurrency", "wallet", "bitcoin cash", "xamine", "integration"]
logo = "https://github.com/XRBitcoinCash/XRBitcoinCash/blob/main/logo.png"

[security]
audited = false
audit_details = ""
bug_bounty = false
contact = "security@xrbitcoincash.com"

[links]
homepage = "https://xrbitcoincash.com"
github = "https://github.com/XRBitcoinCash/XRBitcoinCash"
support = "https://github.com/XRBitcoinCash/XRBitcoinCash/issues"