name: Well-Known & AI Manifests — Validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: wellknown-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate manifests & security surfaces
    runs-on: ubuntu-latest
    steps:
      - run: echo "Temporarily disabled validation; passing stub."
